/* The following code was generated by JFlex 1.6.1 */

package compiladoresfirstproject;

import java_cup.runtime.*;
import javax.swing.*;
import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/JAAM/Documents/NetBeansProjects/CompiladoresFirstProject/src/compiladoresfirstproject/scanner.lex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  1, 34,  2,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     2, 30,  0,  0,  0,  0,  0,  4,  0,  0, 24, 21,  0, 33,  0, 32, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 17, 22, 25,  0, 
     0, 19,  8, 31, 15, 12, 26, 20, 18, 14, 29,  0, 13,  9,  6, 10, 
     0, 28,  7, 16,  5, 23, 11,  0,  0,  0, 27,  0,  0,  0,  0,  0, 
     0, 19,  8, 31, 15, 12, 26, 20, 18, 14, 29,  0, 13,  9,  6, 10, 
     0, 28,  7, 16,  5, 23, 11,  0,  0,  0, 27,  0,  3,  0,  0,  0, 
     0,  0,  0,  0,  0, 34,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\11\1\1\6"+
    "\2\1\1\7\1\1\1\10\1\11\2\1\1\12\1\13"+
    "\11\0\1\14\1\15\5\0\1\16\1\17\1\0\1\20"+
    "\21\0\1\21\1\22\2\0\1\23\5\0\1\24\1\25"+
    "\1\26\4\0\1\27\5\0\1\30\1\0\1\31\1\32"+
    "\1\33\2\0\1\34\2\0\1\35\3\0\1\36\1\37"+
    "\1\40\1\0\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\43\0\43\0\43\0\43\0\106\0\151"+
    "\0\214\0\257\0\322\0\365\0\u0118\0\u013b\0\u015e\0\u0181"+
    "\0\u01a4\0\u01c7\0\43\0\u01ea\0\43\0\u020d\0\u0230\0\u0253"+
    "\0\43\0\43\0\u0276\0\u0299\0\u02bc\0\u02df\0\u0302\0\u0325"+
    "\0\u0348\0\u036b\0\u038e\0\u03b1\0\43\0\u03d4\0\u03f7\0\u041a"+
    "\0\u043d\0\u0460\0\43\0\43\0\u0483\0\43\0\u04a6\0\u04c9"+
    "\0\u04ec\0\u050f\0\u0532\0\u0555\0\u0578\0\u059b\0\u05be\0\u05e1"+
    "\0\u0604\0\u0627\0\u064a\0\u066d\0\u0690\0\u06b3\0\u06d6\0\43"+
    "\0\43\0\u06f9\0\u071c\0\43\0\u073f\0\u0762\0\u0785\0\u07a8"+
    "\0\u07cb\0\43\0\43\0\43\0\u07ee\0\u0811\0\u0834\0\u0857"+
    "\0\43\0\u087a\0\u089d\0\u08c0\0\u08e3\0\u0906\0\43\0\u0929"+
    "\0\43\0\43\0\43\0\u094c\0\u096f\0\43\0\u0992\0\u09b5"+
    "\0\43\0\u09d8\0\u09fb\0\u0a1e\0\43\0\43\0\43\0\u0a41"+
    "\0\43";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\2\2\1\10"+
    "\1\11\1\12\1\2\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\2\1\23\1\24\1\2\1\25"+
    "\1\26\1\27\3\2\1\30\1\2\1\31\1\32\53\0"+
    "\1\33\45\0\1\34\42\0\1\35\3\0\1\36\61\0"+
    "\1\37\13\0\1\40\52\0\1\41\57\0\1\42\23\0"+
    "\1\43\44\0\1\44\52\0\1\45\26\0\1\46\10\0"+
    "\1\47\26\0\1\50\1\51\6\0\1\52\51\0\1\53"+
    "\42\0\1\54\37\0\1\55\45\0\1\56\43\0\1\57"+
    "\52\0\1\60\16\0\1\61\43\0\1\62\40\0\1\63"+
    "\35\0\1\64\43\0\1\65\70\0\1\66\15\0\1\67"+
    "\27\0\1\70\11\0\1\71\51\0\1\72\51\0\1\73"+
    "\25\0\1\74\56\0\1\75\35\0\1\76\41\0\1\77"+
    "\41\0\1\100\51\0\1\101\33\0\1\102\34\0\1\103"+
    "\54\0\1\104\34\0\1\105\47\0\1\106\52\0\1\107"+
    "\27\0\1\110\44\0\1\111\36\0\1\112\53\0\1\113"+
    "\42\0\1\114\35\0\1\115\61\0\1\116\17\0\1\117"+
    "\50\0\1\120\31\0\1\121\40\0\1\122\43\0\1\123"+
    "\46\0\1\124\46\0\1\125\63\0\1\126\12\0\1\127"+
    "\43\0\1\130\44\0\1\131\50\0\1\132\36\0\1\133"+
    "\35\0\1\134\72\0\1\135\23\0\1\136\36\0\1\137"+
    "\50\0\1\140\43\0\1\141\42\0\1\142\33\0\1\143"+
    "\35\0\1\144\56\0\1\145\37\0\1\146\42\0\1\147"+
    "\41\0\1\150\46\0\1\151\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2660];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\5\11\14\1\1\11\1\1\1\11\3\1\2\11"+
    "\11\0\1\1\1\11\5\0\2\11\1\0\1\11\21\0"+
    "\2\11\2\0\1\11\5\0\3\11\4\0\1\11\5\0"+
    "\1\11\1\0\3\11\2\0\1\11\2\0\1\11\3\0"+
    "\3\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  String temp_include;
int columna=1;
  public String sourceFilename;
    StringBuffer string = new StringBuffer();
    int ultimoEstado = 0;
 public void init(){};


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { {return new Symbol(sym.EOF, null); }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Caracter desconocido en la fila " + yyline + ", columna " + yychar);
            }
          case 34: break;
          case 2: 
            { yychar=0;
            }
          case 35: break;
          case 3: 
            { /* ignore white space. */
            }
          case 36: break;
          case 4: 
            { /*no hace nada, aumenta una columna,continua lectura*/yychar++;
            }
          case 37: break;
          case 5: 
            { /* ignore apostrofos. */
            }
          case 38: break;
          case 6: 
            { return new Symbol(sym.MENOR,yyline, yychar, yytext());
            }
          case 39: break;
          case 7: 
            { return new Symbol(sym.SUMA,     yyline, yychar, yytext());
            }
          case 40: break;
          case 8: 
            { return new Symbol(sym.MULTI,       yyline, yychar, yytext());
            }
          case 41: break;
          case 9: 
            { return new Symbol(sym.MAYOR,  yyline, yychar, yytext());
            }
          case 42: break;
          case 10: 
            { return new Symbol(sym.DIV,    yyline, yychar, yytext());
            }
          case 43: break;
          case 11: 
            { return new Symbol(sym.RESTA,    yyline, yychar, yytext());
            }
          case 44: break;
          case 12: 
            { return new Symbol(sym.si,    yyline, yychar, yytext());
            }
          case 45: break;
          case 13: 
            { return new Symbol(sym.MENOR_IGUAL,  yyline, yychar, yytext());
            }
          case 46: break;
          case 14: 
            { return new Symbol(sym.IGUAL_IGUAL,      yyline, yychar, yytext());
            }
          case 47: break;
          case 15: 
            { return new Symbol(sym.MAYOR_IGUAL,        yyline, yychar, yytext());
            }
          case 48: break;
          case 16: 
            { return new Symbol(sym.DIFERENTE,    yyline, yychar, yytext());
            }
          case 49: break;
          case 17: 
            { return new Symbol(sym.True,  yyline, yychar, yytext());
            }
          case 50: break;
          case 18: 
            { return new Symbol(sym.boca,    yyline, yychar, yytext());
            }
          case 51: break;
          case 19: 
            { return new Symbol(sym.ojos, yyline, yychar, yytext());
            }
          case 52: break;
          case 20: 
            { return new Symbol(sym.sino,      yyline, yychar, yytext());
            }
          case 53: break;
          case 21: 
            { return new Symbol(sym.hola,    yyline, yychar, yytext());
            }
          case 54: break;
          case 22: 
            { return new Symbol(sym.haga,yyline, yychar, yytext());
            }
          case 55: break;
          case 23: 
            { return new Symbol(sym.mover, yyline, yychar, yytext());
            }
          case 56: break;
          case 24: 
            { return new Symbol(sym.decir,    yyline, yychar, yytext());
            }
          case 57: break;
          case 25: 
            { return new Symbol(sym.abajo,    yyline, yychar, yytext());
            }
          case 58: break;
          case 26: 
            { return new Symbol(sym.adios,     yyline, yychar, yytext());
            }
          case 59: break;
          case 27: 
            { return new Symbol(sym.False,      yyline, yychar, yytext());
            }
          case 60: break;
          case 28: 
            { return new Symbol(sym.lindos, yyline, yychar, yytext());
            }
          case 61: break;
          case 29: 
            { return new Symbol(sym.arriba, yyline, yychar, yytext());
            }
          case 62: break;
          case 30: 
            { return new Symbol(sym.derecha,    yyline, yychar, yytext());
            }
          case 63: break;
          case 31: 
            { return new Symbol(sym.mientras,     yyline, yychar, yytext());
            }
          case 64: break;
          case 32: 
            { return new Symbol(sym.entonces,    yyline, yychar, yytext());
            }
          case 65: break;
          case 33: 
            { return new Symbol(sym.izquierda,     yyline, yychar, yytext());
            }
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
