
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package compiladoresfirstproject;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int mover = 6;
  public static final int lindos = 28;
  public static final int MENOR = 9;
  public static final int haga = 24;
  public static final int adios = 27;
  public static final int SUMA = 15;
  public static final int MENOR_IGUAL = 11;
  public static final int True = 19;
  public static final int MULTI = 17;
  public static final int mientras = 23;
  public static final int sino = 25;
  public static final int MAYOR_IGUAL = 12;
  public static final int False = 20;
  public static final int izquierda = 2;
  public static final int ojos = 30;
  public static final int arriba = 3;
  public static final int IGUAL_IGUAL = 13;
  public static final int MAYOR = 10;
  public static final int EOF = 0;
  public static final int hola = 26;
  public static final int DIFERENTE = 14;
  public static final int boca = 29;
  public static final int entonces = 22;
  public static final int DIV = 18;
  public static final int NEWLINE = 8;
  public static final int error = 1;
  public static final int decir = 7;
  public static final int abajo = 5;
  public static final int derecha = 4;
  public static final int si = 21;
  public static final int RESTA = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "izquierda",
  "arriba",
  "derecha",
  "abajo",
  "mover",
  "decir",
  "NEWLINE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "True",
  "False",
  "si",
  "entonces",
  "mientras",
  "haga",
  "sino",
  "hola",
  "adios",
  "lindos",
  "boca",
  "ojos"
  };
}

