/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladoresfirstproject;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JAAM
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Path pathDeArchivo;
    String retornoArchivo;
    
    Boolean bandera;
    Boolean bandera2;
    
    AnalizadorMain nuevoAnalizador;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.nuevoAnalizador = new AnalizadorMain();
        this.bandera = false;
        this.bandera2 = false;
        initComponents();
        txtCodigo.setEditable(false);
        salidaText.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargar = new javax.swing.JButton();
        procesarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        salidaText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        generarBnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargar.png"))); // NOI18N
        btnCargar.setText("Cargar Archivo");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        procesarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        procesarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/scanner.png"))); // NOI18N
        procesarBtn.setText("Procesar");
        procesarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarBtnActionPerformed(evt);
            }
        });

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        jScrollPane1.setViewportView(txtCodigo);

        salidaText.setColumns(20);
        salidaText.setRows(5);
        jScrollPane2.setViewportView(salidaText);

        jLabel1.setFont(new java.awt.Font("appleberry", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrada.png"))); // NOI18N
        jLabel1.setText("Entrada");

        jLabel2.setFont(new java.awt.Font("appleberry", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        jLabel2.setText("Salida");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        generarBnt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generarBnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generar.png"))); // NOI18N
        generarBnt.setText("Generar Código");
        generarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(procesarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(generarBnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(procesarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(generarBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        JFileChooser Buscador = new JFileChooser();
        Buscador.setAcceptAllFileFilterUsed(false);
        Buscador.setMultiSelectionEnabled(false);
        Buscador.setFileFilter(new FileNameExtensionFilter("Doc txt", "txt"));
        Buscador.showOpenDialog(Buscador);
        File file = Buscador.getSelectedFile();
        try {
            pathDeArchivo = Paths.get(file.getAbsolutePath());
            retornoArchivo = new String(Files.readAllBytes(pathDeArchivo));
            txtCodigo.setText("");
            txtCodigo.setText(retornoArchivo);
            bandera = true;
            //abrir.setText(retorno);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No Conseguimos Cargar El Archivo");
        }
    }//GEN-LAST:event_btnCargarActionPerformed
     
     public void rotularError() {
         JOptionPane.showMessageDialog(this, "Errores detectados, revisar módulo de errores");
     }
    
    private void procesarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarBtnActionPerformed
        
        if(bandera == true) {
            nuevoAnalizador.procesarEntrada(pathDeArchivo.toString());
            bandera = false;
            bandera2 = true;
        } else {
            JOptionPane.showMessageDialog(this, "Debe Cargarse Un Archivo");
        }     
    }//GEN-LAST:event_procesarBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiarTextView();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBntActionPerformed
        // TODO add your handling code here:
        if(bandera2 == true) {
                nuevoAnalizador.GenerarCodigo();
                bandera2 = false;
        } else {
            JOptionPane.showMessageDialog(this, "Generate Error");
        }
        
    }//GEN-LAST:event_generarBntActionPerformed

    
    /**
     */
    //</editor-fold>

    /* Create and display the form */
    public void run() {
        new VentanaPrincipal().setVisible(true);
    }
    
    public static void mostrarSalida(String pEntrada){
     //salidaText.setText( salidaText.getText() + pEntrada + "\n");
     salidaText.append(pEntrada + "\n");
    }
    
    private void limpiarTextView() {
        salidaText.setText("");
        txtCodigo.setText("");
    }
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton generarBnt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton procesarBtn;
    public static javax.swing.JTextArea salidaText;
    public static javax.swing.JTextArea txtCodigo;
    // End of variables declaration//GEN-END:variables
  
}
